// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.PasswordStrength
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("strength")]
        public string Strength { get; set; }

        [JsonProperty("passwordInfo")]
        public PasswordInfo PasswordInfo { get; set; }
    }

    public partial class PasswordInfo
    {
        [JsonProperty("length")]
        public long Length { get; set; }

        [JsonProperty("hasSpecialCharacters")]
        public bool HasSpecialCharacters { get; set; }

        [JsonProperty("hasNumbers")]
        public bool HasNumbers { get; set; }

        [JsonProperty("hasLowercase")]
        public bool HasLowercase { get; set; }

        [JsonProperty("hasUppercase")]
        public bool HasUppercase { get; set; }

        [JsonProperty("hasSpaces")]
        public bool HasSpaces { get; set; }
    }
}
